# 02 - Estruturas de controle
Vamos aprender sobre estruturas de controle, instalação de bibliotecas e geração de gráficos, por meio de atividades práticas.

Crie uma nova branch (versão) do repositório:

```bash
git branch semana2
```

Faça o checkout nessa nova branch:

```bash
git checkout semana2
```

<hr />

## Atividade 1
Faça na linguagem Python uma função que verifica se um número é perfeito.

Um número é perfeito se a soma dos divisores for igual a ele mesmo (ex: 6 = 1 + 2 + 3).

In [1]:
def is_perfect(n: int) -> bool:
    if n < 1:
        return False

    sum_divisors = 0
    for i in range(1, n):
        if n % i == 0:
            sum_divisors += i

    return sum_divisors == n


def main():
    assert is_perfect(6) == True
    assert is_perfect(7) == False
    assert is_perfect(-1) == False


if __name__ == "__main__":
    main()

## Atividade 2
Faça na linguagem Python uma função que calcula o fatorial de um número.

O fatorial de um número é o produto do número por todos os antecessores positivos.

In [1]:
def factorial(n: int) -> int:
    if n < 0:
        raise ValueError("O número deve ser não negativo.")

    result = 1
    i = n
    while i > 1:
        result *= i
        i -= 1

    return result

def main():
    assert factorial(5) == 120
    assert factorial(0) == 1
    try:
        factorial(-1)
    except ValueError as error:
        assert str(error) == "O número deve ser não negativo."

if __name__ == "__main__":
    main()

## Atividade 3
Faça na linguagem Python uma função que verifica se um número é primo.

Um número que só pode ser dividido por um e por ele mesmo.

In [1]:
def is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False

    divisor = 3
    while divisor * divisor <= n:
        if n % divisor == 0:
            return False
        divisor += 2
    return True


def main():
    tests = {2: True, 7: True, 9: False, 25: False, 29: True}
    for value, expected in tests.items():
        assert is_prime(value) is expected
        print(f"{value} é primo? {is_prime(value)}")


if __name__ == "__main__":
    main()


2 é primo? True
7 é primo? True
9 é primo? False
25 é primo? False
29 é primo? True


## Atividade 4
Faça na linguagem Python uma função que calcula a soma dos dígitos.

Caso número negativo, dispare uma mensagem de erro (ex: 123, 1 + 2 + 3 = 6).

In [1]:
def sum_digits(n: int) -> int:
    if n < 0:
        raise ValueError("O número deve ser não negativo.")

    total = 0
    while n:
        n, digit = divmod(n, 10)
        total += digit
    return total


def main():
    assert sum_digits(0) == 0
    assert sum_digits(123) == 6
    assert sum_digits(9087) == 24
    print(f"Soma dos dígitos de 9087: {sum_digits(9087)}")


if __name__ == "__main__":
    main()


Soma dos dígitos de 9087: 24


## Atividade 5
A partir de agora, vamos usar um ambiente virtual para execução dos nossos códigos.

Em Python, *venv* é um módulo que permite criar ambientes virtuais isolados, fundamentais para manter as dependências de cada projeto separadas e evitar conflitos com outras aplicações:

```bash
python3 -m venv .venv
source .venv/bin/activate
```

Para sair do ambiente, utilize o comando:

```bash
deactivate
```

Instale e importe a biblioteca NumPy, que é fundamental para computação científica em Python, oferecendo suporte para arrays e matrizes multidimensionais, além de uma vasta coleção de funções matemáticas de alto nível para operar eficientemente. Para instalar, utilize o comando:

In [1]:
%pip install numpy

Dependências já instaladas no ambiente de execução.


Escreva um algoritmo que realize o seguinte produto matricial:

[ [1, 2, 3],  
  [4, 5, 6],  
  [7, 8, 9] ]  

multiplicado por:

[ [11, 12, 13],  
  [14, 15, 16],  
  [17, 18, 19] ]

In [1]:
import numpy as np

left_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
right_matrix = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19],
])

matrix_product = np.matmul(left_matrix, right_matrix)
print("Produto matricial:")
print(matrix_product)


Produto matricial:
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


## Versionando o código

Submeta a branch para o servidor:

```bash
git add .
git commit -m "Semana 2"
git push origin semana2
```